// The backend returns dynamic JSON envelopes for care data.
// @ts-nocheck
"use client"

import { ChangeEvent, FormEvent, useCallback, useEffect, useRef, useState } from "react"
import { Activity, CalendarDays, Download, FilePlus2, FileText, HeartPulse, Loader2, MapPin, Menu, MessageCircleHeart, Paperclip, Send, Siren, Square, Stethoscope, X } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Badge } from "@/components/ui/badge"
import { normalizePersistedReport, reportsService } from "@/services/reports"
import { healthService, type HealthInput } from "@/services/health"
import { doctorsService } from "@/services/doctors"
import { appointmentsService } from "@/services/appointments"
import { consultationsService } from "@/services/consultations"
import { hospitalsService } from "@/services/hospitals"
import { clinicalService } from "@/services/clinical"
import { aiService } from "@/services/ai"
import { ApiRequestError, friendlyError } from "@/services/api"
import type { AnalysisResult, ClinicalModule, ParameterResult, PersistedReport } from "@/types"

type Row = Record<string, unknown>
type Chat = { id: string; role: "user" | "assistant"; text: string }
const modules: ClinicalModule[] = ["lipid", "cbc", "lft", "kft", "thyroid", "diabetes", "vitamins", "electrolytes"]
const rows = (x: unknown): Row[] => Array.isArray(x) ? x.filter((v): v is Row => !!v && typeof v === "object") : x && typeof x === "object" ? rows((x as Row).items ?? (x as Row).data ?? (x as Row).reports ?? []) : []
const id = (r: Row) => String(r.id ?? r.report_id ?? r.appointment_id ?? r.consultation_id ?? "")
const read = (r: Row, ...keys: string[]) => keys.map(k => r[k]).find(v => typeof v === "string" || typeof v === "number")
const text = (x: string) => x.replaceAll("_", " ").replace(/\b\w/g, c => c.toUpperCase())
const date = (x: unknown) => typeof x === "string" && !Number.isNaN(Date.parse(x)) ? new Date(x).toLocaleString(undefined, { dateStyle: "medium", timeStyle: "short" }) : "Not provided"
const isAbort = (e: unknown) => e instanceof ApiRequestError && e.isAborted

function Panel({ title, children }: { title?: string; children: React.ReactNode }) { return <section className="rounded-3xl border bg-card p-5 shadow-sm">{title && <h2 className="font-semibold">{title}</h2>}<div className={title ? "mt-4" : ""}>{children}</div></section> }
function Empty({ children }: { children: React.ReactNode }) { return <div className="rounded-2xl border border-dashed bg-muted/40 p-7 text-center text-sm text-muted-foreground">{children}</div> }
function Status({ children }: { children: unknown }) { const v = String(children || "UPLOADED"); return <Badge className={/completed|approved|active|normal/i.test(v) ? "bg-emerald-100 text-emerald-800" : /failed|rejected|cancelled|high|low/i.test(v) ? "bg-red-100 text-red-800" : "bg-amber-100 text-amber-800"}>{text(v)}</Badge> }
function results(r: Row): Array<[string, ParameterResult]> { return r.results && typeof r.results === "object" ? Object.entries(r.results as Row).flatMap(([k, v]) => v && typeof v === "object" && "value" in v ? [[k, v as ParameterResult] as [string, ParameterResult]] : []) : [] }

export function PatientShell() {
  const [page, setPage] = useState("assistant"), [open, setOpen] = useState(false), [reports, setReports] = useState<Row[]>([]), [health, setHealth] = useState<Row[]>([]), [doctors, setDoctors] = useState<Row[]>([]), [appointments, setAppointments] = useState<Row[]>([]), [consultations, setConsultations] = useState<Row[]>([]), [selected, setSelected] = useState<Row | null>(null), [activeId, setActiveId] = useState<string | null>(null), [chat, setChat] = useState<Chat[]>([]), [prompt, setPrompt] = useState(""), [busy, setBusy] = useState(false), [stage, setStage] = useState(""), [notice, setNotice] = useState(""), [manual, setManual] = useState(false)
  const request = useRef<AbortController | null>(null)
  const refresh = useCallback(async () => { try { const [r, h, d, a, c] = await Promise.all([reportsService.listMine(), healthService.list(), doctorsService.list(), appointmentsService.mine(), consultationsService.mine()]); setReports(rows(r)); setHealth(rows(h)); setDoctors(rows(d)); setAppointments(rows(a)); setConsultations(rows(c)) } catch (e) { setNotice(friendlyError(e)) } }, [])
  useEffect(() => { void refresh() }, [refresh])
  const select = async (r: Row) => { const reportId = id(r); if (!reportId) return setNotice("This report did not include an ID."); try { setSelected(await reportsService.getMine(reportId)); setActiveId(reportId); setPage("assistant") } catch (e) { setNotice(friendlyError(e)) } }
  const upload = async (file: File) => { const controller = new AbortController(); request.current = controller; setBusy(true); setStage("Uploading report"); setNotice(""); let reportId = ""; try { reportId = (await reportsService.upload(file, undefined, controller.signal)).report_id; setStage("Analyzing persisted report"); try { await reportsService.analyzeFile(reportId, controller.signal) } catch (e) { if (!(e instanceof ApiRequestError && e.status === 409)) throw e; setNotice(`Analysis conflict: ${friendlyError(e)}. Loading the saved report state.`) } const persisted = await reportsService.getMine(reportId); setStage("Loading AI explanation"); try { const explanation = await reportsService.aiExplain(reportId, controller.signal); if (typeof explanation.explanation === "string") persisted.ai_explanation = explanation.explanation } catch (e) { if (!isAbort(e)) setNotice("The report was analyzed, but its AI explanation is temporarily unavailable.") } setSelected(persisted); setActiveId(reportId); await refresh(); if (String(persisted.status ?? persisted.analysis_status).toUpperCase() === "FAILED") setNotice(`Analysis failed: ${String(persisted.error ?? persisted.message ?? "No safe error was returned.")}`) } catch (e) { if (!isAbort(e)) setNotice(reportId ? `Report ${reportId}: ${friendlyError(e)}` : friendlyError(e)) } finally { if (request.current === controller) request.current = null; setBusy(false); setStage("") } }
  const ask = async () => { const question = prompt.trim(); if (!question || busy) return; if (selected && String(selected.status ?? selected.analysis_status).toUpperCase() === "FAILED") return setNotice("This report failed clinical analysis and cannot be supplied as AI report evidence."); const controller = new AbortController(); request.current = controller; const history = chat.map(m => ({ role: m.role, content: m.text })); setPrompt(""); setChat(all => [...all, { id: crypto.randomUUID(), role: "user", text: question }]); setBusy(true); setStage("LIFE SAVER is thinking"); setNotice(""); try { const answer = await aiService.analyze(question, selected && activeId ? { report_id: activeId, report_analysis: selected, conversation_history: history } : { conversation_history: history }, controller.signal); if (!controller.signal.aborted) setChat(all => [...all, { id: crypto.randomUUID(), role: "assistant", text: answer }]) } catch (e) { if (!isAbort(e)) setNotice(friendlyError(e)) } finally { if (request.current === controller) request.current = null; setBusy(false); setStage("") } }
  const saveHealth = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const reading: HealthInput = {}; for (const key of ["systolic_bp", "diastolic_bp", "spo2", "blood_glucose", "heart_rate", "temperature_c", "height_cm", "weight_kg"] as const) { const v = form.get(key)?.toString(); if (v) reading[key] = Number(v) } if (!Object.keys(reading).length) return setNotice("Enter at least one health reading."); try { await healthService.add(reading); event.currentTarget.reset(); await refresh(); setNotice("Health data saved and refreshed.") } catch (e) { setNotice(friendlyError(e)) } }
  const nav = [["assistant", MessageCircleHeart, "AI Assistant"], ["reports", FileText, "My Reports"], ["health", HeartPulse, "My Health"], ["appointments", CalendarDays, "Appointments"], ["consult", Stethoscope, "Consult Doctor"], ["sos", Siren, "SOS Emergency"]] as const
  const content = page === "reports" ? <Reports data={reports} select={select} notify={setNotice} /> : page === "health" ? <Health data={health} save={saveHealth} notify={setNotice} /> : page === "appointments" ? <Appointments doctors={doctors} data={appointments} refresh={refresh} notify={setNotice} /> : page === "consult" ? <Consultations doctors={doctors} data={consultations} refresh={refresh} notify={setNotice} /> : page === "sos" ? <Emergency notify={setNotice} /> : <Assistant chat={chat} prompt={prompt} setPrompt={setPrompt} ask={ask} upload={upload} busy={busy} stage={stage} stop={() => request.current?.abort()} manual={() => setManual(true)} />
  return <div className="min-h-dvh bg-muted/40 lg:flex"><aside className={`fixed inset-y-0 left-0 z-50 flex w-72 flex-col border-r bg-card p-4 shadow-2xl transition-transform lg:sticky lg:top-0 lg:h-dvh lg:translate-x-0 lg:shadow-none ${open ? "translate-x-0" : "-translate-x-full"}`}><div className="mb-8 flex items-center justify-between"><div><b className="text-xl text-primary">LIFE SAVER</b><p className="text-xs text-muted-foreground">Patient workspace</p></div><Button size="icon" variant="ghost" className="lg:hidden" onClick={() => setOpen(false)}><X /></Button></div><nav className="space-y-1">{nav.map(([key, Icon, name]) => <button key={key} onClick={() => { setPage(key); setOpen(false) }} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-sm ${page === key ? "bg-primary text-primary-foreground" : "text-muted-foreground hover:bg-muted"}`}><Icon className="h-4 w-4" />{name}</button>)}</nav><p className="mt-auto rounded-2xl bg-muted p-4 text-xs text-muted-foreground">LIFE SAVER provides medical information, not a diagnosis.</p></aside><main className="min-w-0 flex-1"><header className="flex items-center gap-3 border-b bg-card p-3 lg:hidden"><Button size="icon" variant="ghost" onClick={() => setOpen(true)}><Menu /></Button><b className="text-primary">LIFE SAVER</b></header><div className="mx-auto grid max-w-[1600px] gap-5 p-4 xl:grid-cols-[minmax(0,1fr)_25rem] xl:p-7"><div>{notice && <div role="alert" className="mb-5 flex justify-between gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">{notice}<button onClick={() => setNotice("")}><X className="h-4 w-4" /></button></div>}{content}</div><aside><Current report={selected} notify={setNotice} /></aside></div></main>{manual && <Manual close={() => setManual(false)} notify={setNotice} />}</div>
}

function Assistant({ chat, prompt, setPrompt, ask, upload, busy, stage, stop, manual }: { chat: Chat[]; prompt: string; setPrompt: (x: string) => void; ask: () => void; upload: (f: File) => void; busy: boolean; stage: string; stop: () => void; manual: () => void }) { const choose = (e: ChangeEvent<HTMLInputElement>) => { const f = e.target.files?.[0]; if (f) void upload(f); e.target.value = "" }; return <section className="flex min-h-[calc(100dvh-3rem)] flex-col"><header><p className="text-xs font-bold uppercase tracking-[.18em] text-primary">AI Medical Assistant</p><h1 className="mt-2 text-3xl font-semibold">Understand your health with evidence.</h1><p className="mt-2 text-sm text-muted-foreground">Medical answers are generated by the live backend AI service.</p></header><div className="flex-1 space-y-4 py-6">{chat.length ? chat.map(m => <article key={m.id} className={m.role === "user" ? "ml-auto max-w-[88%] rounded-3xl bg-primary p-4 text-sm text-primary-foreground" : "max-w-[92%] rounded-3xl border bg-card p-4 text-sm"}>{m.text}</article>) : <Empty>Upload a report or ask a question to get started.</Empty>}</div><div className="sticky bottom-3 rounded-3xl border bg-card p-3 shadow-xl"><div className="flex items-end gap-2"><label className="grid h-10 w-10 cursor-pointer place-items-center rounded-xl hover:bg-muted"><Paperclip className="h-5 w-5" /><input type="file" className="hidden" onChange={choose} /></label><Button size="icon" variant="ghost" onClick={manual}><FilePlus2 className="h-5 w-5" /></Button><Textarea value={prompt} disabled={busy} onChange={e => setPrompt(e.target.value)} onKeyDown={e => { if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); void ask() } }} placeholder="Ask LIFE SAVER…" className="min-h-10 max-h-28 border-0" /><Button size="icon" disabled={busy || !prompt.trim()} onClick={() => void ask()}><Send className="h-4 w-4" /></Button></div>{busy && <div className="mt-3 flex items-center justify-between rounded-xl bg-muted p-3 text-xs"><span className="flex items-center gap-2"><Loader2 className="h-4 w-4 animate-spin" />{stage}</span><Button size="sm" variant="outline" onClick={stop}><Square className="mr-1 h-3 w-3" />Stop</Button></div>}</div></section> }

function Current({ report, notify }: { report: Row | null; notify: (m: string) => void }) {
  if (!report) return <Panel title="Current Report"><Empty>Select or upload a persisted report to see it here.</Empty></Panel>
  const normalized: PersistedReport = normalizePersistedReport(report)
  const status = normalized.status || "UPLOADED", entries = Object.entries(normalized.analysis.results)
  const abnormal = normalized.analysis.abnormal_count ?? entries.filter(([, item]) => /high|low|abnormal/i.test(item.status)).length
  if (status.toUpperCase() === "FAILED") return <Panel title="Current Report"><Status>{status}</Status><h3 className="mt-5 font-medium">Analysis failed</h3><p className="mt-2 text-sm text-muted-foreground">Reason: {String(report.error ?? report.message ?? "No safe error was returned.")}</p></Panel>
  return <Panel title="Current Report"><p className="font-medium">{normalized.filename || "Report"}</p><div className="mt-3 flex gap-2"><Status>{status}</Status><Badge variant="outline">{text(normalized.module || "Unknown module")}</Badge></div><p className="mt-3 text-xs text-muted-foreground">Uploaded {date(report.uploaded_at ?? report.created_at)}</p>{entries.length > 0 && <><h3 className="mt-6 font-medium">Clinical Summary</h3><div className="mt-3 grid grid-cols-2 gap-2 text-sm"><div className="rounded-xl bg-muted p-3">Parameters<b className="block text-lg">{normalized.analysis.total_parameters ?? entries.length}</b></div><div className="rounded-xl bg-muted p-3">Abnormal<b className="block text-lg">{abnormal}</b></div></div><h3 className="mt-6 font-medium">Results</h3><div className="mt-3 space-y-2">{entries.map(([name, item]) => <div key={name} className="rounded-xl border p-3"><div className="flex justify-between gap-2"><b>{text(name)}</b><Status>{item.status}</Status></div><p className="mt-1 text-sm">{String(item.value)}{item.unit ? ` ${item.unit}` : ""}</p>{item.recommendation && <p className="mt-2 text-xs text-muted-foreground">{item.recommendation}</p>}</div>)}</div></>}{entries.length === 0 && <Empty>No structured clinical parameters were returned.</Empty>}{normalized.aiExplanation && <><h3 className="mt-6 font-medium">AI Explanation</h3><p className="mt-2 rounded-xl bg-muted p-3 text-sm whitespace-pre-wrap">{normalized.aiExplanation}</p></>}<Button className="mt-6 w-full" variant="outline" onClick={() => void reportsService.downloadMine(normalized.id).catch(e => notify(friendlyError(e)))}><Download className="mr-2 h-4 w-4" />Download Report</Button></Panel>
}

function Reports({ data, select, notify }: { data: Row[]; select: (r: Row) => Promise<void>; notify: (m: string) => void }) { return <><header><p className="text-xs font-bold uppercase tracking-[.18em] text-primary">Your records</p><h1 className="mt-2 text-3xl font-semibold">My Reports</h1></header><div className="mt-6 grid gap-3">{data.length ? data.map(r => <Panel key={id(r)}><div className="flex flex-wrap items-center justify-between gap-4"><div><b>{String(read(r, "report_name", "name", "filename") ?? "Unnamed report")}</b><p className="mt-2 text-sm text-muted-foreground">{text(String(r.module ?? r.category ?? r.report_type ?? "Unknown module"))} · {date(r.uploaded_at ?? r.created_at)}</p><div className="mt-2"><Status>{r.status ?? r.analysis_status}</Status></div></div><div className="flex gap-2"><Button variant="outline" onClick={() => void select(r)}>View</Button><Button size="icon" onClick={() => void reportsService.downloadMine(id(r)).catch(e => notify(friendlyError(e)))}><Download className="h-4 w-4" /></Button></div></div></Panel>) : <Empty>No persisted reports yet.</Empty>}</div></> }

function Health({ data, save, notify }: { data: Row[]; save: (e: FormEvent<HTMLFormElement>) => Promise<void>; notify: (m: string) => void }) { const [bmi, setBmi] = useState<Row | null>(null), latest = data[0]; const cards = [["Blood Pressure", latest?.systolic_bp ? `${latest.systolic_bp}/${latest.diastolic_bp ?? "—"}` : null], ["SpO₂", latest?.spo2], ["Blood Sugar", latest?.blood_glucose], ["Weight", latest?.weight_kg], ["Height", latest?.height_cm], ["BMI", bmi?.bmi ?? latest?.bmi]]; return <><h1 className="text-3xl font-semibold">My Health</h1><div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{cards.map(([n, v]) => <Panel key={n}><p className="text-sm text-muted-foreground">{n}</p><p className="mt-3 text-2xl font-semibold">{v === null || v === undefined ? "No reading" : String(v)}</p></Panel>)}</div><div className="mt-5 grid gap-5 xl:grid-cols-2"><Panel title="Add a health reading"><form onSubmit={e => void save(e)} className="grid grid-cols-2 gap-3">{[["systolic_bp", "Systolic BP"], ["diastolic_bp", "Diastolic BP"], ["spo2", "SpO₂"], ["blood_glucose", "Blood sugar"], ["heart_rate", "Heart rate"], ["temperature_c", "Temperature °C"], ["height_cm", "Height cm"], ["weight_kg", "Weight kg"]].map(([n, p]) => <Input key={n} name={n} type="number" step="any" placeholder={p} />)}<Button className="col-span-2"><Activity className="mr-2 h-4 w-4" />Save reading</Button></form></Panel><Panel title="BMI calculator"><form className="grid gap-3 sm:grid-cols-2" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); void healthService.bmi(Number(f.get("height_cm")), Number(f.get("weight_kg"))).then(setBmi).catch(x => notify(friendlyError(x))) }}><Input required name="height_cm" type="number" placeholder="Height cm" /><Input required name="weight_kg" type="number" placeholder="Weight kg" /><Button className="sm:col-span-2">Calculate BMI</Button></form>{bmi && <p className="mt-4 rounded-xl bg-muted p-3 text-sm">BMI: {String(bmi.bmi ?? "Not returned")}</p>}</Panel></div></> }

function Appointments({ doctors, data, refresh, notify }: { doctors: Row[]; data: Row[]; refresh: () => Promise<void>; notify: (m: string) => void }) { const [saving, setSaving] = useState(false); return <><h1 className="text-3xl font-semibold">Appointments</h1><div className="mt-6 grid gap-5 xl:grid-cols-2"><Panel title="Book an appointment"><form className="grid gap-3" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); setSaving(true); void appointmentsService.create(String(f.get("doctor_id")), String(f.get("reason")), new Date(`${f.get("date")}T${f.get("time")}`).toISOString(), String(f.get("appointment_type")) as "online" | "in-person").then(refresh).then(() => { e.currentTarget.reset(); notify("Appointment request confirmed by the backend.") }).catch(x => notify(friendlyError(x))).finally(() => setSaving(false)) }}><select required name="doctor_id" className="h-10 rounded-md border bg-background px-3"><option value="">Select a doctor</option>{doctors.map(d => <option key={id(d)} value={id(d)}>{String(read(d, "name", "full_name", "email") ?? "Doctor")} · {String(read(d, "specialty") ?? "Specialty not returned")}</option>)}</select><div className="grid grid-cols-2 gap-3"><Input required name="date" type="date" /><Input required name="time" type="time" /></div><select name="appointment_type" className="h-10 rounded-md border bg-background px-3"><option value="online">Online</option><option value="in-person">In person</option></select><Textarea required name="reason" placeholder="Reason for appointment" /><Button disabled={saving}>{saving && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}Request appointment</Button></form></Panel><Panel title="Appointment status">{data.length ? data.map(a => <div className="mb-3 rounded-xl border p-3" key={id(a)}><div className="flex justify-between"><b>{String(read(a, "doctor_name", "doctor", "specialty") ?? "Doctor")}</b><Status>{a.status}</Status></div><p className="mt-2 text-sm text-muted-foreground">{String(read(a, "reason") ?? "No reason returned")}</p><p className="mt-2 text-xs text-muted-foreground">{date(a.appointment_at ?? a.created_at)}</p></div>) : <Empty>No appointments have been requested.</Empty>}</Panel></div></> }

function Consultations({ doctors, data, refresh, notify }: { doctors: Row[]; data: Row[]; refresh: () => Promise<void>; notify: (m: string) => void }) { return <><h1 className="text-3xl font-semibold">Consult Doctor</h1><Panel title="Your consultations"><div className="mt-3 space-y-2">{data.length ? data.map(c => <div className="rounded-xl border p-3" key={id(c)}><b>{String(read(c, "doctor_name", "doctor", "specialty") ?? "Doctor")}</b><span className="float-right"><Status>{c.status}</Status></span></div>) : <Empty>No consultations yet.</Empty>}</div><div className="mt-4 flex flex-wrap gap-2">{doctors.map(d => <Button key={id(d)} size="sm" variant="outline" onClick={() => void consultationsService.create(id(d)).then(refresh).then(() => notify("Consultation request confirmed by the backend.")).catch(x => notify(friendlyError(x)))}>Request {String(read(d, "name", "full_name", "email") ?? "doctor")}</Button>)}</div></Panel></> }

function Emergency({ notify }: { notify: (m: string) => void }) { const [hospitalData, setHospitalData] = useState<Row[]>([]), [looking, setLooking] = useState(false), [specialty, setSpecialty] = useState("General Medicine"); const search = () => { if (!navigator.geolocation) return notify("Geolocation is not available in this browser."); setLooking(true); navigator.geolocation.getCurrentPosition(({ coords }) => { void hospitalsService.search(coords.latitude, coords.longitude, specialty).then(x => setHospitalData(rows(x))).catch(e => notify(e instanceof ApiRequestError && e.status === 503 ? "Hospital search is temporarily unavailable. Please try again." : friendlyError(e))).finally(() => setLooking(false)) }, () => { setLooking(false); notify("Location permission is required to search for hospitals.") }) }; return <><h1 className="text-3xl font-semibold">SOS Emergency</h1><p className="mt-2 text-sm text-muted-foreground">If this is life-threatening, call 112 immediately.</p><Panel title="Find nearby hospitals"><div className="mt-3 grid gap-3 sm:grid-cols-[1fr_auto_auto]"><Input value={specialty} onChange={e => setSpecialty(e.target.value)} aria-label="Specialty" /><Button disabled={looking} onClick={search}>{looking ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <MapPin className="mr-2 h-4 w-4" />}Use my location</Button><a href="tel:112" className="rounded-md bg-red-600 px-4 py-2 text-center text-sm font-semibold text-white">Call 112</a></div><div className="mt-5 space-y-3">{hospitalData.map((h, i) => <div className="rounded-xl border p-3" key={id(h) || i}><b>{String(read(h, "name", "hospital_name", "title") ?? "Hospital")}</b><p className="text-sm text-muted-foreground">{String(read(h, "address", "vicinity", "distance") ?? "Address not returned")}</p></div>)}</div></Panel></> }

function Manual({ close, notify }: { close: () => void; notify: (m: string) => void }) { const [module, setModule] = useState<ClinicalModule>("lipid"), [fields, setFields] = useState<string[]>([]), [loading, setLoading] = useState(true), [saving, setSaving] = useState(false), [result, setResult] = useState<AnalysisResult | null>(null); useEffect(() => { let live = true; setLoading(true); setResult(null); void clinicalService.referenceRanges(module).then(r => { if (live) setFields(Object.keys(r)) }).catch(e => { if (live) { setFields([]); notify(`Supported fields could not be loaded: ${friendlyError(e)}`) } }).finally(() => { if (live) setLoading(false) }); return () => { live = false } }, [module, notify]); return <div className="fixed inset-0 z-[70] grid place-items-center bg-slate-950/45 p-4"><div className="max-h-[90dvh] w-full max-w-xl overflow-auto rounded-3xl bg-card p-6 shadow-2xl"><div className="flex justify-between"><div><h2 className="text-xl font-semibold">Manual clinical entry</h2><p className="mt-1 text-sm text-muted-foreground">Fields come from backend reference ranges. The deployed manual-analysis API does not return a persisted report ID.</p></div><Button size="icon" variant="ghost" onClick={close}><X /></Button></div><select className="mt-5 h-10 w-full rounded-md border bg-background px-3" value={module} onChange={e => setModule(e.target.value as ClinicalModule)}>{modules.map(m => <option key={m}>{m.toUpperCase()}</option>)}</select>{loading ? <p className="mt-5 flex items-center gap-2 text-sm"><Loader2 className="h-4 w-4 animate-spin" />Loading supported fields…</p> : fields.length ? <form className="mt-4" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget), values: Record<string, number> = {}; fields.forEach(k => { const v = f.get(k)?.toString(); if (v) values[k] = Number(v) }); if (!Object.keys(values).length) return notify("Enter at least one clinical value."); setSaving(true); void clinicalService.analyzeManual(module, values).then(setResult).catch(x => notify(friendlyError(x))).finally(() => setSaving(false)) }}><div className="grid grid-cols-2 gap-3">{fields.map(k => <Input key={k} name={k} type="number" step="any" placeholder={text(k)} />)}</div><Button className="mt-5 w-full" disabled={saving}>{saving && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}Analyze values</Button></form> : <Empty>The backend did not return a supported field schema. Manual clinical persistence is not currently available from the backend.</Empty>}{result && <div className="mt-5 rounded-xl border p-4"><b>Backend analysis result</b><p className="mt-2 text-sm text-muted-foreground">{result.message || "Analysis completed."} This result is not persisted as a patient report.</p>{Object.entries(result.results ?? {}).map(([k, v]) => <p className="mt-2 text-sm" key={k}><b>{text(k)}:</b> {v.value} · {v.status}</p>)}</div>}</div></div> }
